---
title: "MA415/615 EDA Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# SUPPRESS GLOBAL WARNING
options(warn = -1)

# SET TO ONE DIGIT AFTER DECIMAL POINT
options(digits = 2)

# PREPARE PACKAGES
if (!require("pacman")) install.packages("pacman")
pacman::p_load("dplyr", "ggplot2", "tibble", "tidyr", "readxl", "reshape2")

#downloading data

download.file(
  "https://www.eia.gov/consumption/residential/data/2015/hc/hc3.7.xlsx",
  "NORTH_MID.xlsx", quiet = TRUE, mode = "wb")


download.file(
  "https://www.eia.gov/consumption/residential/data/2015/hc/hc3.8.xlsx",
  "SOUTH_WEST.xlsx", quiet = TRUE, mode = "wb")

#selecting data 
NM_size <- read_excel("NORTH_MID.xlsx", sheet = "data", range = "A108:H113",
                          col_names = FALSE, col_types = "text")

NM_type <- read_excel("NORTH_MID.xlsx", sheet = "data", range = "A115:H121",
                          col_names = FALSE, col_types = "text")

# NM_age <- read_excel("NORTH_MID.xlsx", sheet = "data", range = "A123:H129",
                          # col_names = FALSE, col_types = "text")

SW_size <- read_excel("SOUTH_WEST.xlsx", sheet = "data", range = "A111:K116",
                          col_names = FALSE, col_types = "text")

SW_type <- read_excel("SOUTH_WEST.xlsx", sheet = "data", range = "A118:K124",
                          col_names = FALSE, col_types = "text")

# SW_age <- read_excel("SOUTH_WEST.xlsx", sheet = "data", range = "A126:K132",
                          # col_names = FALSE, col_types = "text")

```

```{r}
#create duplicate data for future use
NM_size_1 <- NM_size

NM_type_1 <- NM_type

# NM_age_1 <- NM_age

SW_size_1 <- SW_size

SW_type_1 <- SW_type

# SW_age_1 <- SW_age

#rename column's names
colnames(NM_size_1)      <- c("RFG_SIZE", "TTL_US", "TTL_NE",
                           "N_ENG", "MID_ATL", "TTL_MID_WEST",
                           "EN_CENT", "WN_CENT")

colnames(NM_type_1)      <- c("RFG_TYPE", "TTL_US", "TTL_NE",
                           "N_ENG", "MID_ATL", "TTL_MID_WEST",
                           "EN_CENT", "WN_CENT")

# colnames(NM_age_1)      <- c("RFG_AGE", "TTL_US", "TTL_NE",
                           # "N_ENG", "MID_ATL", "TTL_MID_WEST",
                           # "EN_CENT", "WN_CENT")

colnames(SW_size_1)      <- c("RFG_SIZE", "TTL_US", "TTL_SOUTH",
                           "S_ATL", "ES_CENT", "WS_CENT",
                           "TTL_WEST", "TTL_MOUNT", "MOUNT_N",
                           "MOUNT_SOUTH", "PACIF")

colnames(SW_type_1)      <- c("RFG_TYPE", "TTL_US", "TTL_SOUTH",
                           "S_ATL", "ES_CENT", "WS_CENT",
                           "TTL_WEST", "TTL_MOUNT", "MOUNT_N",
                           "MOUNT_SOUTH", "PACIF")

# colnames(SW_age_1)      <- c("RFG_AGE", "TTL_US", "TTL_SOUTH",
                           # "S_ATL", "ES_CENT", "WS_CENT",
                           # "TTL_WEST", "TTL_MOUNT", "MOUNT_N",
                           # "MOUNT_SOUTH", "PACIF")

#Saving total column for future use
NM_size_TTL <- within(NM_size_1,rm(TTL_US,N_ENG,MID_ATL,EN_CENT,WN_CENT))
NM_type_TTL <- within(NM_type_1,rm(TTL_US,N_ENG,MID_ATL,EN_CENT,WN_CENT))

SW_size_TTL <- within(SW_size_1,rm(TTL_US,S_ATL,ES_CENT,WS_CENT,TTL_MOUNT,MOUNT_N,MOUNT_SOUTH,PACIF))
SW_type_TTL <- within(SW_type_1,rm(TTL_US,S_ATL,ES_CENT,WS_CENT,TTL_MOUNT,MOUNT_N,MOUNT_SOUTH,PACIF))

```

```{r}

#Drop the Unnecessary Column

NM_size_2 <- within(NM_size_1, rm(TTL_US,TTL_NE,TTL_MID_WEST))
NM_type_2 <- within(NM_type_1, rm(TTL_US,TTL_NE,TTL_MID_WEST))
# NM_age_2 <- within(NM_age_1, rm(TTL_US,TTL_NE))
SW_size_2 <- within(SW_size_1, rm(TTL_US,TTL_SOUTH,TTL_WEST,TTL_MOUNT))
SW_type_2 <- within(SW_type_1, rm(TTL_US,TTL_SOUTH,TTL_WEST,TTL_MOUNT))
# SW_age_2 <- within(SW_age_1, rm(TTL_US,TTL_SOUTH,TTL_WEST,TTL_MOUNT))



# COERCE FRIDGE TYPE COLUMN TO FACTOR
NM_size_2$RFG_SIZE    <- as.factor(NM_size_2$RFG_SIZE)
NM_type_2$RFG_TYPE    <- as.factor(NM_type_2$RFG_TYPE)
# NM_age_2$RFG_AGE    <- as.factor(NM_age_2$RFG_AGE)
SW_size_2$RFG_SIZE    <- as.factor(SW_size_2$RFG_SIZE)
SW_type_2$RFG_TYPE    <- as.factor(SW_type_2$RFG_TYPE)
# SW_age_2$RFG_AGE    <- as.factor(SW_age_2$RFG_AGE)

NM_size_TTL$RFG_SIZE    <- as.factor(NM_size_TTL$RFG_SIZE)
NM_type_TTL$RFG_TYPE    <- as.factor(NM_type_TTL$RFG_TYPE)
SW_size_TTL$RFG_SIZE    <- as.factor(SW_size_TTL$RFG_SIZE)
SW_type_TTL$RFG_TYPE    <- as.factor(SW_type_TTL$RFG_TYPE)


#cleaning data, mark unknown data as N/A
NM_size_2[, 2:5]    <- sapply(NM_size_2[, 2:5], as.numeric)
NM_type_2[, 2:5]    <- sapply(NM_type_2[, 2:5], as.numeric)
# NM_age_2[, 2:6]    <- sapply(NM_age_2[, 2:6], as.numeric)
SW_size_2[, 2:7]    <- sapply(SW_size_2[, 2:7], as.numeric)
SW_type_2[, 2:7]    <- sapply(SW_type_2[, 2:7], as.numeric)
# SW_age_2[, 2:7]    <- sapply(SW_age_2[, 2:7], as.numeric)
NM_size_TTL[, 2:3]    <- sapply(NM_size_TTL[, 2:3], as.numeric)
NM_type_TTL[, 2:3]    <- sapply(NM_type_TTL[, 2:3], as.numeric)

SW_size_TTL[, 2:3]    <- sapply(SW_size_TTL[, 2:3], as.numeric)
SW_type_TTL[, 2:3]    <- sapply(SW_type_TTL[, 2:3], as.numeric)

#rename columns
colnames(NM_size_2)      <- c("RFG_SIZE",
                           "N_ENG", "MID_ATL",
                           "EN_CENT", "WN_CENT")

colnames(NM_type_2)      <- c("RFG_TYPE", 
                           "N_ENG", "MID_ATL", 
                           "EN_CENT", "WN_CENT")

# colnames(NM_age_2)      <- c("RFG_AGE", 
                           # "N_ENG", "MID_ATL", 
                           # "EN_CENT", "WN_CENT")

colnames(SW_size_2)      <- c("RFG_SIZE", 
                           "S_ATL", "ES_CENT", "WS_CENT",
                           "MOUNT_N",
                           "MOUNT_SOUTH", "PACIF")

colnames(SW_type_2)      <- c("RFG_TYPE", 
                           "S_ATL", "ES_CENT", "WS_CENT",
                           "MOUNT_N",
                           "MOUNT_SOUTH", "PACIF")

# colnames(SW_age_2)      <- c("RFG_AGE", 
                           # "S_ATL", "ES_CENT", "WS_CENT",
                            # "MOUNT_N",
                           # "MOUNT_SOUTH", "PACIF")

```

```{r}

#Melting Data 
NM_size_3 <- as_tibble(melt(NM_size_2, id = 1))
NM_type_3 <- as_tibble(melt(NM_type_2, id = 1))
# NM_age_3 <- as_tibble(melt(NM_age_2, id = 1))
SW_size_3 <- as_tibble(melt(SW_size_2, id = 1))
SW_type_3 <- as_tibble(melt(SW_type_2, id = 1))
# SW_age_3 <- as_tibble(melt(SW_age_2, id = 1))
NM_size_TTL <- as_tibble(melt(NM_size_TTL, id = 1))
NM_type_TTL <- as_tibble(melt(NM_type_TTL, id = 1))
SW_size_TTL <- as_tibble(melt(SW_size_TTL, id = 1))
SW_type_TTL <- as_tibble(melt(SW_type_TTL, id = 1))



#Update column's name
names(NM_size_3)[2]    <- "Region"
names(NM_type_3)[2]    <- "Region"
# names(NM_age_3)[2]    <- "Region"
names(SW_size_3)[2]    <- "Region"
names(SW_type_3)[2]    <- "Region"
# names(SW_age_3)[2]    <- "Region"
names(NM_size_TTL)[2]    <- "Region"
names(NM_type_TTL)[2]    <- "Region"
names(SW_size_TTL)[2]    <- "Region"
names(SW_type_TTL)[2]    <- "Region"

names(NM_size_3)[3]    <- "Number of Unit"
names(NM_type_3)[3]    <- "Number of Unit"
# names(NM_age_3)[3]    <- "Number of Unit"
names(SW_size_3)[3]    <- "Number of Unit"
names(SW_type_3)[3]    <- "Number of Unit"
# names(SW_age_3)[3]    <- "Number of Unit"
names(NM_size_TTL)[3]    <- "Number of Unit"
names(NM_type_TTL)[3]    <- "Number of Unit"
names(SW_size_TTL)[3]    <- "Number of Unit"
names(SW_type_TTL)[3]    <- "Number of Unit"



```

```{r}

#getting sum of data
NM_size_SUM <- aggregate(NM_size_3$`Number of Unit`, 
                           by = list(category = NM_size_3$`Region`),
                           FUN=sum, na.rm = TRUE)

NM_type_SUM <- aggregate(NM_type_3$`Number of Unit`, 
                           by = list(category = NM_type_3$`Region`),
                           FUN=sum, na.rm = TRUE)

# NM_age_SUM <- aggregate(NM_age_3$`Number of Unit`, 
                           # by = list(category = NM_age_3$`Region`),
                           # FUN=sum, na.rm = TRUE)

SW_size_SUM <- aggregate(SW_size_3$`Number of Unit`, 
                           by = list(category = SW_size_3$`Region`),
                           FUN=sum, na.rm = TRUE)

SW_type_SUM <- aggregate(SW_type_3$`Number of Unit`, 
                           by = list(category = SW_type_3$`Region`),
                           FUN=sum, na.rm = TRUE)

# SW_age_SUM <- aggregate(SW_age_3$`Number of Unit`, 
                           # by = list(category = SW_age_3$`Region`),
                           # FUN=sum, na.rm = TRUE)

#Rename Columns
names(NM_size_SUM)[1] <- "Region"
names(NM_size_SUM)[2] <- "Total Number of Unit"

names(NM_type_SUM)[1] <- "Region"
names(NM_type_SUM)[2] <- "Total Number of Unit"

# names(NM_age_SUM)[1] <- "Region"
# names(NM_age_SUM)[2] <- "Total Number of Unit"

names(SW_size_SUM)[1] <- "Region"
names(SW_size_SUM)[2] <- "Total Number of Unit"

names(SW_type_SUM)[1] <- "Region"
names(SW_type_SUM)[2] <- "Total Number of Unit"

# names(SW_age_SUM)[1] <- "Region"
# names(SW_age_SUM)[2] <- "Total Number of Unit"

#Merge Sum with Original Data
TTL_NM_size <- merge(x = NM_size_3, y = NM_size_SUM, by = "Region", all = TRUE)
names(TTL_NM_size)[3] <- "Number of Unit"
names(TTL_NM_size)[4] <- "Total Number of Unit by Region"
TTL_NM_size$Percentage <- 100*(TTL_NM_size$`Number of Unit` /TTL_NM_size$`Total Number of Unit by Region`)
rm(list = ls(pattern = "^T_"))

TTL_NM_type <- merge(x = NM_type_3, y = NM_type_SUM, by = "Region", all = TRUE)
names(TTL_NM_type)[3] <- "Number of Unit"
names(TTL_NM_type)[4] <- "Total Number of Unit by Region"
TTL_NM_type$Percentage <- 100*(TTL_NM_type$`Number of Unit` /TTL_NM_type$`Total Number of Unit by Region`)
rm(list = ls(pattern = "^T_"))

# TTL_NM_age <- merge(x = NM_age_3, y = NM_age_SUM, by = "Region", all = TRUE)
# names(TTL_NM_age)[3] <- "Number of Unit"
# names(TTL_NM_age)[4] <- "Total Number of Unit by Region"
# TTL_NM_age$Percentage <- 100*(TTL_NM_age$`Number of Unit` /TTL_NM_age$`Total Number of Unit by Region`)
# rm(list = ls(pattern = "^T_"))

TTL_SW_size <- merge(x = SW_size_3, y = SW_size_SUM, by = "Region", all = TRUE)
names(TTL_SW_size)[3] <- "Number of Unit"
names(TTL_SW_size)[4] <- "Total Number of Unit by Region"
TTL_SW_size$Percentage <- 100*(TTL_SW_size$`Number of Unit` /TTL_SW_size$`Total Number of Unit by Region`)
rm(list = ls(pattern = "^T_"))

TTL_SW_type <- merge(x = SW_type_3, y = SW_type_SUM, by = "Region", all = TRUE)
names(TTL_SW_type)[3] <- "Number of Unit"
names(TTL_SW_type)[4] <- "Total Number of Unit by Region"
TTL_SW_type$Percentage <- 100*(TTL_SW_type$`Number of Unit` /TTL_SW_type$`Total Number of Unit by Region`)
rm(list = ls(pattern = "^T_"))

# TTL_SW_age <- merge(x = SW_age_3, y = SW_age_SUM, by = "Region", all = TRUE)
# names(TTL_SW_age)[3] <- "Number of Unit"
# names(TTL_SW_age)[4] <- "Total Number of Unit by Region"
# TTL_SW_age$Percentage <- 100*(TTL_SW_age$`Number of Unit` /TTL_SW_age$`Total Number of Unit by Region`)
# rm(list = ls(pattern = "^T_"))

TTL_size <- merge(x = NM_size_TTL, y = SW_size_TTL, by = c("RFG_SIZE","Region","Number of Unit"), all = TRUE)
TTL_type <- merge(x = NM_type_TTL, y = SW_type_TTL, by = c("RFG_TYPE","Region","Number of Unit"), all = TRUE)
rm(list = ls(pattern = "^T_"))

```

```{r}
#Start plotting
PLOT_NM_SIZE_PERC <- ggplot(data = TTL_NM_size, aes(x = `Region`, y = Percentage)) +
                 geom_col(aes(fill = `RFG_SIZE`)) +
                 labs(title = "Percentage of Northeast and Midwest regions, 2015") +
                 coord_flip()

PLOT_NM_SIZE <- ggplot(data = TTL_NM_size, aes(x = `Region`, y = `Number of Unit`)) +
             geom_col(aes(fill = `RFG_SIZE`)) +
             theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             labs(title = "Appliances in homes in the Northeast and Midwest regions, 2015")

PLOT_NM_TYPE_PERC <- ggplot(data = TTL_NM_type, aes(x = `Region`, y = Percentage)) +
                 geom_col(aes(fill = `RFG_TYPE`)) +
                 labs(title = "Percentage of Northeast and Midwest regions, 2015") +
                 coord_flip()

PLOT_NM_TYPE <- ggplot(data = TTL_NM_type, aes(x = `Region`, y = `Number of Unit`)) +
             geom_col(aes(fill = `RFG_TYPE`)) +
             theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             labs(title = "Appliances in homes in the Northeast and Midwest regions, 2015")

# PLOT_NM_AGE_PERC <- ggplot(data = TTL_NM_age, aes(x = `Region`, y = Percentage)) +
                 # geom_col(aes(fill = `RFG_AGE`)) +
                 # labs(y = "Percentage") +
                 # coord_flip()

# PLOT_NM_AGE <- ggplot(data = TTL_NM_age, aes(x = `Region`, y = `Number of Unit`)) +
             # geom_col(aes(fill = `RFG_AGE`)) +
             # theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             # labs(title = "Appliances in homes in the Northeast and Midwest regions, 2015")

###########

PLOT_SW_SIZE_PERC <- ggplot(data = TTL_SW_size, aes(x = `Region`, y = Percentage)) +
                 geom_col(aes(fill = `RFG_SIZE`)) +
                 labs(title = "Percentage of South and West regions, 2015") +
                 coord_flip()

PLOT_SW_SIZE <- ggplot(data = TTL_SW_size, aes(x = `Region`, y = `Number of Unit`)) +
             geom_col(aes(fill = `RFG_SIZE`)) +
             theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             labs(title = "Appliances in homes in the South and West regions, 2015")

PLOT_SW_TYPE_PERC <- ggplot(data = TTL_SW_type, aes(x = `Region`, y = Percentage)) +
                 geom_col(aes(fill = `RFG_TYPE`)) +
                 labs(title = "Percentage of South and West regions, 2015") +
                 coord_flip()

PLOT_SW_TYPE <- ggplot(data = TTL_SW_type, aes(x = `Region`, y = `Number of Unit`)) +
             geom_col(aes(fill = `RFG_TYPE`)) +
             theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             labs(title = "Appliances in homes in the South and West regions, 2015")

# PLOT_SW_AGE_PERC <- ggplot(data = TTL_SW_age, aes(x = `Region`, y = Percentage)) +
                 # geom_col(aes(fill = `RFG_AGE`)) +
                 # labs(y = "Percentage") +
                 # coord_flip()

# PLOT_SW_AGE <- ggplot(data = TTL_SW_age, aes(x = `Region`, y = `Number of Unit`)) +
             # geom_col(aes(fill = `RFG_AGE`)) +
             # theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             # labs(title = "Appliances in homes in the South and West regions, 2015")

######

PLOT_SIZE_TTL <- ggplot(data = TTL_size, aes(x = `Region`, y = `Number of Unit`)) +
             geom_col(aes(fill = `RFG_SIZE`)) +
             theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             labs(title = "Appliances of refrigerator size in homes in U.S big regions, 2015")

PLOT_TYPE_TTL <- ggplot(data = TTL_type, aes(x = `Region`, y = `Number of Unit`)) +
             geom_col(aes(fill = `RFG_TYPE`)) +
             theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
             labs(title = "Appliances of refrigerator type in homes in U.S big regions, 2015")

```




```{r}
#export result
PLOT_SIZE_TTL
PLOT_TYPE_TTL

PLOT_NM_SIZE
PLOT_NM_SIZE_PERC
PLOT_NM_TYPE
PLOT_NM_TYPE_PERC


PLOT_SW_SIZE
PLOT_SW_SIZE_PERC
PLOT_SW_TYPE
PLOT_SW_TYPE_PERC





```



