---
title: "“Worldwide Ocean Temperature EDA""
author: "Xiaoqian Xue, Sibo Zhu,  Li Liu,  Danni Fu"
date: "2017/11/6"
output: pdf_document
---

#EDA Part
```{r}
matrix.jan.temp = NULL
matrix.aug.temp  = NULL

#### the following loop will generate the graphs 
##### and it will build two matrices to track the average temprtures of two months through out the 16 years. 
for (k in 2001:2016) {
  YEAR = k
  
  load(paste0("./cleaned_data/ave_temp_",YEAR,".Rdata"))
  plot(EDA.year[,2], type = "l",  main = paste("Average Sea Tempreture of", YEAR, sep = " ") , xlab = "Month", ylab =    "Temperature(C)", col = "blue")
  
  plot(EDA.year[,3], type = "l",  main = paste("Average Air Tempreture of", YEAR, sep = " ") , xlab = "Month", ylab =    "Temperature(C)", col = "red")
  
  jan.temp = EDA.year[1,2:3]
  aug.temp = EDA.year[8,2:3]
  #jan.temp = cbind(YEAR, jan.temp)
  matrix.aug.temp = rbind(matrix.aug.temp , aug.temp)
  matrix.jan.temp = rbind(matrix.jan.temp , jan.temp)
}

colnames(matrix.jan.temp) = c("Sea Temp" , "Air Temp")
rownames(matrix.jan.temp) = c("2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016")

colnames(matrix.aug.temp) = c("Sea Temp" , "Air Temp")
rownames(matrix.aug.temp) = c("2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016")


```



```{r}

###### graphing the average tempruturs of JAN AND JUL across 16 years in a gragh. 

#lines(matrix.jan.temp[,1])
plot(matrix.jan.temp[,1], type = "l",  main = "Average Sea Tempreture of Jaunuary" , xlab = "Year", ylab = "Temperature", col = "red")
plot(matrix.jan.temp[,2], type = "l",  main = "Average Air Tempreture of Jaunuary" , xlab = "Year", ylab = "Temperature", col = "blue")

plot(matrix.aug.temp[,2], type = "l",  main = "Average Air Tempreture of August" , xlab = "Year", ylab = "Temperature", col = "red")

plot(matrix.aug.temp[,1], type = "l",  main = "Average Sea Tempreture of August" , xlab = "Year", ylab = "Temperature", col = "blue")

```

```{r}

```
